spring.application.name=onlybuns-back


#Databese setings
spring.datasource.url=jdbc:postgresql://localhost:5432/isa
spring.datasource.username=postgres
spring.datasource.password=super
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Email settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=onlybunsapp@gmail.com
spring.mail.password=xydupvvxyoackdcn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

file.upload-dir=uploads/images
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB